WEB/03_django/00_django_intro/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    # 사용자가 index/로 요청을 보내면 views.py에 있는 index라는 이름의 함수를 호출 할겁니다!
    path('index/practice/', views.index, name='index'),
    path('detail/', views.detail, name='detail'),
    path('dtl-practice/', views.dtl_practice, name='dtl'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    # str은 기본값! (생략 가능)
    path('hello/<str:name>/<name2>/', views.hello, name='hello'),    
    path('food/<name>/<int:num>/', views.food, name='food'),
]

WEB/03_django/00_django_intro/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
]

WEB/03_django/00_django_intro/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('index/', views.index, name='index'),
]

WEB/03_django/00_django_intro/articles/views.py
from unittest import result
from django.shortcuts import render

def index(request):
    # request -> 요청과 관련된 다양한 정보가 들어가 있는 객체구나! (HttpRequest라는 클래스의 인스턴스)
    # print(dir(request))
    # print(request.user)
    context = {
        'name': 'JUSTIN',
        'hobby': 'pizza',
    }
    # template을 찾는 기본 원칙 
    # - app 밑에 있는 'templates'라는 이름의 폴더 내부에서 .html 파일을 찾아 렌더링한다.
    # - 하지만 app이 여러 개 있는 경우는 위에서부터 .html 파일을 찾아가기 때문에 동일한 이름이라면
    # settings.py INSTALLED_APPS에 등록된 선순위 앱의 .html 파일을 먼저 읽어오게 된다.
    # - 그렇기 때문에 각 앱 이름으로 templates 내부를 한번 더 래핑한다. 
    # ex 1) articles -> templates/articles/index.html
    # ex 2) pages -> templates/pages/index.html

    # -> render 함수의 두번째 인자를 부를 때 articles/index.html or pages/index.html 처럼 불러야 한다!
    # 왜? 그냥 부르면 기본값은 app 아래 있는 templates에서 해당하는 파일의 이름을 찾기 때문이다!

    return render(request, 'articles/index.html', context)

def detail(request):
    return render(request, 'articles/detail.html')

def dtl_practice(request):
    foods = ['짜장면', '탕수육', '짬뽕', '양장피']
    fruits = ['apple', 'banana', 'cucumber', 'mango']
    user_list = []
    context = {
        'foods': foods,
        'fruits': fruits,
        'user_list': user_list,
    }
    return render(request, 'articles/dtl_practice.html', context)

def throw(request):
    return render(request, 'articles/throw.html')

def catch(request):
    # print(dir(request))
    print(request.GET.get('ball'))
    result = request.GET.get('ball')
    context = {
        'result': result,
    }
    return render(request, 'articles/catch.html', context)

def hello(request, name, name2):
    print(name)
    print(name2)

def food(request, name, num):
    print(type(num))
    context = {
        'food': name,
        'num': num,
    }
    return render(request, 'articles/food.html', context)

WEB/03_django/00_django_intro/pages/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'pages/index.html')

WEB/03_django/00_django_intro/articles/templates/articles/_card.html
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div>

WEB/03_django/00_django_intro/articles/templates/articles/_carousel.html
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
</div>
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
</div>
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
</div>
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
</div>

WEB/03_django/00_django_intro/articles/templates/articles/catch.html
{% extends 'base.html' %}

{% block content %}
<h2>{{ result }}</h2>
{% comment %} <a href="/articles/throw/">[뒤로가기]</a> {% endcomment %}
<a href="{% url 'articles:throw' %}">[뒤로가기]</a>

{% comment %} <a href="/articles/dtl-practice/">[DTL 연습한 곳으로 가자]</a> {% endcomment %}
<a href="{% url 'articles:dtl' %}">[DTL 연습한 곳으로 가자]</a>

{% comment %} <a href="/articles/index/">[articles 페이지의 인덱스로 가기]</a> {% endcomment %}
{% comment %} app_name:path_name {% endcomment %}
<a href="{% url 'articles:index' %}">[articles 페이지의 인덱스로 가기]</a>

<a href="{% url 'pages:index' %}">[pages 페이지의 인덱스로 가기]</a>
{% endblock %}

WEB/03_django/00_django_intro/articles/templates/articles/detail.html
{% comment %} https://docs.djangoproject.com/en/4.0/ref/templates/builtins/#extends {% endcomment %}
{% extends 'base.html' %}

{% block content %}
  <h2>이건 detail.html입니다.</h2>
  <p>base.html을 상속</p>
  {% comment %} 
   https://docs.djangoproject.com/en/4.0/ref/templates/builtins/#include
  {% endcomment %}
  {% comment %} 카드 로직 {% endcomment %}
  <div class="container">
    {% include "_card.html" %}
  </div>
  {% comment %} 캐러셀 로직 {% endcomment %}
  {% include "_carousel.html" %}
{% endblock content %}

WEB/03_django/00_django_intro/articles/templates/articles/dtl_practice.html
{% extends 'base.html' %}

{% block content %}
  {% comment %}  
    https://docs.djangoproject.com/en/4.0/ref/templates/builtins/#std:templatetag-for
  {% endcomment %}
  <h3>1. for</h3>
  {% for food in foods %}
    <p>{{ food }}</p>
  {% endfor %}
  <hr>

  {% for food in foods %}
    <p>{{ forloop.counter0 }} {{ food }}</p>
  {% endfor %}
  <hr>

  {% for user in empty_list %}
    <p>{{ user }}</p>
  {% comment %} https://docs.djangoproject.com/en/4.0/ref/templates/builtins/#for-empty {% endcomment %}
  {% empty %}
    <p>지금 가입한 유저가 없습니다.</p>
  {% endfor %}
  <hr>


  <h3>2. if</h3>
  {% if '짜장면' in foods %}
    <p>짜장면엔 고추가루지 !</p>
  {% endif %}
  <hr>

  {% for food in foods %}
    {% if forloop.first %}
      <p>짜장면+고추가루</p>
    {% else %}
      <p>{{ food }}</p>
    {% endif %}
  {% endfor %}
  <hr>

  {% comment %} https://docs.djangoproject.com/en/4.0/ref/templates/builtins/#in-operator {% endcomment %}
  <p>3. length filter 활용</p>
  {% for fruit in fruits %}
    {% if fruit|length > 5 %}
      <p>이름이 너무 길어요.</p>
    {% else %}
      <p>{{ fruit }}, {{ fruit|length }}</p>
    {% endif %}
  {% endfor %}
  <hr>

  <h3>4. lorem ipsum</h3>
  {% lorem %}
  <hr>
  {% lorem 3 w %}
  <hr>
  {% lorem 4 w random %}
  <hr>
  {% lorem 2 p %}
  <hr>

  <h3>5. 글자 관련 필터</h3>
  <p>{{ 'ABC'|lower }}</p>
  <p>{{ my_sentence|title }}</p>
  <p>{{ foods|random }}</p>
  <hr>  

  {% comment %} 
   - 사용 x!!!!!!!!!!! -> 연산은 view에서 끝내고 결과를 받아 보여주는게 일반적 
   - 기본적인 연산은 view에서 다 하고 template은 보여주는 일만 하는 게 맞다!
   {% endcomment %}
  <h3>6. 연산</h3>
  <p>{{ 4|add:6 }}</p>
  <hr>

  {% comment %} https://docs.djangoproject.com/en/4.0/ref/templates/builtins/#date {% endcomment %}
  <h3>7. 다양한 날짜 표현</h3>
  {% now "DATETIME_FORMAT" %}<br>
  {% now "SHORT_DATETIME_FORMAT" %}<br>
  {% now "DATE_FORMAT" %}<br>
  {% now "SHORT_DATE_FORMAT" %}
  <hr>
  {% now "Y년 m월 d일 (D) h:i" %}
  <hr>
  {% now "Y" as current_year %}
  Copyright {{ current_year }}
  <hr>

  <a href="/index/">back</a>
{% endblock %}

WEB/03_django/00_django_intro/articles/templates/articles/food.html
{% extends 'base.html' %}

{% block content %}
<h2>저는 {{ food }}을 {{ num }}배 만큼 먹고 싶습니다.</h2>
{% endblock %}

WEB/03_django/00_django_intro/articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>My first Django application</h1>
  <h2>하하 나는 이제 장고 개발자 하하하</h2>
  <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Esse, assumenda! Dolore cum vitae pariatur laboriosam atque ea repudiandae et quisquam amet laborum? Accusantium, officiis necessitatibus nemo alias tenetur aliquid a.</p>
  <hr>

  <h2>{{ name|lower }}</h2>
  <h2>{{ hobby|length }}</h2>
</body>
</html>

WEB/03_django/00_django_intro/articles/templates/articles/throw.html
{% extends 'base.html' %}

{% block content %}
{% comment %} 
  공을 던질 수 있도록 폼을 준비하자!
{% endcomment %}

{% comment %} 
  action -> 어디로 공을 던질지!
  method -> 어떤 방식으로 던질지(단순 조회가 GET)
{% endcomment %}
<form action="/articles/catch/" method="GET">
  {% comment %} 
    name -> 어떤 박스에 담아서 던지지 결정!
    name의 값은 박스의 이름을 의미한다!  
  {% endcomment %}
  <input type="text" name="ball">
  <input type="submit" value="공을 던지자!">
</form>
{% endblock %}

WEB/03_django/00_django_intro/mypjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

WEB/03_django/00_django_intro/pages/templates/pages/index.html
{% extends 'base.html' %}

{% block content %}
<h2>나는 pages의 index!!!</h2>
{% endblock %}